services:
  nas-api:
    image: qunhuinas:latest
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - TOKEN=${TOKEN}
      - DSM_HOST=${DSM_HOST:-127.0.0.1}
      - NAS_USER=${NAS_USER:-admin}
      - DSM_PORT=${DSM_PORT:-5000}
      - DSM_HTTPS=${DSM_HTTPS:-true}
      - NAS_PASSWORD=${NAS_PASSWORD}
    restart: unless-stopped


